---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios'
    msg: "Network device OS not defined or not supported by this role: {{ ansible_network_os }}"

- name: Configure ospf global settings
  nxos_ospf_vrf:
    ospf: "{{ item.value.ospf.ospf_id | default(item.value.name) }}"
    state: "{{ item.value.ospf.state | default(omit) }}"
    router_id: "{{ item.value.ospf.router_id | default(omit) }}"
    vrf: "{{ item.value.name | default(omit) }}"
    auto_cost: "{{ item.value.ospf.auto_cost | default(omit) }}"
    default_metric: "{{ item.value.ospf.def_metric | default(omit) }}"
    log_adjacency: "{{ item.value.ospf.log_adj | default(omit) }}"
    passive_interface: "{{ item.value.ospf.passive_interface | default(omit) }}"
    timer_throttle_lsa_hold: "{{ item.value.ospf.timer_throttle_lsa_hold | default(omit) }}"
    timer_throttle_lsa_max: "{{ item.value.ospf.timer_throttle_lsa_max | default(omit) }}"
    timer_throttle_lsa_start: "{{ item.value.ospf.timer_throttle_lsa_start | default(omit) }}"
    timer_throttle_spf_hold: "{{ item.value.ospf.timer_throttle_spf_hold | default(omit) }}"
    timer_throttle_spf_max: "{{ item.value.ospf.timer_throttle_spf_max | default(omit) }}" 
    timer_throttle_spf_start: "{{ item.value.ospf.timer_throttle_spf_start | default(omit) }}"
  loop: "{{ vrfs | dict2items }}"
  when: >
    ansible_network_os == 'nxos' and  
    item.value.ospf is defined
  tags: 
    - ospf_config
    - nxos

- name: Configure ospf interface settings
  nxos_interface_ospf:
    interface: "{{ item.value.name }}"
    ospf: "{{ item.value.ospf.ospf_id }}"  
    area: "{{ item.value.ospf.area_id }}"
    state: "{{ item.value.ospf.state | default(omit) }}"
    cost: "{{ item.value.ospf.cost | default(omit) }}"
    dead_interval: "{{ item.value.ospf.dead_interval | default(omit) }}"     
    hello_interval: "{{ item.value.ospf.hello_interval | default(omit) }}"
    message_digest: "{{ item.value.ospf.message_digest | default(omit) }}"
    message_digest_algorithm_type: "{{ item.value.ospf.md_alg_type | default(omit) }}"
    message_digest_encryption_type: "{{ item.value.ospf.md_encrypt_type | default(omit) }}"
    message_digest_key_id: "{{ item.value.ospf.md_key_id | default(omit) }}"
    message_digest_password: "{{ item.value.ospf.md_password | default(omit) }}"
    passive_interface: "{{ item.value.ospf.passive_interface | default(omit) }}"    
  loop: "{{ interfaces | dict2items }}"
  when: >
    ansible_network_os == 'nxos' and  
    item.value.ospf is defined
  tags: 
    - ospf_config
    - nxos  